---
# handlers file for es
- name: reload systemd configuration
  become: true
  command: systemctl daemon-reload

# Restart kernel parameter
- name: restart kernel parameter
  shell:
    cmd: sudo sysctl -p


# Restart service and ensure it is enabled

- name: restart elasticsearch
  systemd: name=elasticsearch state=restarted enabled=yes
